data bytes or json from bytes
gagliardetto/solana-go pull request #90
Opened 2022-07-13 17:48 UTC by DimaCantemir

added ability to create DataBytesOrJSON struct directly from base64 bytes. Useful when you receive an account though alternative channels, like Geyser plugin + graph protocol,  and need to reconstruct it with as little overhead as possible

2022-07-14 09:40 UTC, gagliardetto commented on rpc/types.go
> +func DataBytesOrJSONFromBase64Bytes(data []byte) (*DataBytesOrJSON, error) {
```suggestion

// DataBytesOrJSONFromBase64Bytes creates a new `DataBytesOrJSON` from the provided base64 bytes.
func DataBytesOrJSONFromBase64Bytes(b64Data []byte) (*DataBytesOrJSON, error) {
```

2022-07-18 14:25 UTC, aspin commented
could we get a bump on this @gagliardetto ?

2022-07-18 14:32 UTC, gagliardetto commented on rpc/types.go
> +			Content:  b64Data,
```suggestion
			Content:  content,
```

2022-07-18 15:08 UTC, gagliardetto commented
In that case, your PR content won't solve your problem.

Can't you just `DataBytesOrJSONFromBase64(string(encodedData))` ?

2022-07-18 15:16 UTC, gagliardetto commented
In that case you have the **A** case, and need to create a `DataBytesOrJSON`. I see.

2022-07-18 15:19 UTC, gagliardetto commented on rpc/types.go
>  	}, nil
```suggestion
	}
```

2022-07-18 16:09 UTC, gagliardetto commented on rpc/types.go
> +func DataBytesOrJSONFromBytes(b64Data []byte) *DataBytesOrJSON {
```suggestion
// DataBytesOrJSONFromBytes creates a new `DataBytesOrJSON` from the provided bytes.
func DataBytesOrJSONFromBytes(data []byte) *DataBytesOrJSON {
```

2022-07-18 16:09 UTC, gagliardetto commented on rpc/types.go
> +			Content:  b64Data,
```suggestion
			Content:  data,
```

2022-07-18 16:17 UTC, gagliardetto commented
LGTM, just need to address the couple above naming changes.

2022-07-18 16:22 UTC, DimaCantemir commented
Done

2022-07-18 16:31 UTC, gagliardetto requested changes

2022-07-18 16:31 UTC, gagliardetto commented on rpc/types.go
> +// DataBytesOrJSONFromBytes creates a new `DataBytesOrJSON` from the provided base64 bytes.
```suggestion
// DataBytesOrJSONFromBytes creates a new `DataBytesOrJSON` from the provided bytes.
```

2022-07-18 16:31 UTC, gagliardetto commented on rpc/types.go
> +	return DataBytesOrJSONFromBytes(b64Data), nil
```suggestion
	decodedData, err := base64.StdEncoding.DecodeString(stringBase64)
	if err != nil {
		return nil, err
	}
	return DataBytesOrJSONFromBytes(decodedData), nil
```

2022-07-18 16:32 UTC, gagliardetto commented
Still missing the change in the comment.

If you go to the "Files changed" tab, you can commit suggestions directly.

2022-07-18 16:36 UTC, DimaCantemir commented
Done. When you merge this could you please tag a new release ? our devOps people are itching to run some performance tests after we integrate this change

2022-07-18 18:03 UTC, merged

2022-07-18 18:06 UTC, gagliardetto commented
No release is scheduled for today.

You can use the latest source with your changes by `go get github.com/gagliardetto/solana-go@8bd6977469ecb5bbd8a27488648b82bd1904f5fe`